### PR TITLE
hitting enter in the password field should connect to obs

### PR DESCRIPTION
**Pull request by captainwasabi**
Issue #9 & #11

### CODE REVIEW

**Comment by you-win** [comment]
Let me know when this is ready to merge. Thanks for the contributions to the plugin-side of things!

**Comment by captainwasabi** [comment]
I think they are all ready.  The only thing that I think could have unintended consequences is the waiting_for_response flag handling changes, but I haven't noticed any issues with it. 

I actually didn't realize that it was pulling every check-in I made to the master branch on my fork into this PR.    I'm guessing to prevent that I need to fork then branch, then merge the branch back to head when it's ready for PR.

**Comment by you-win** [comment]
I'm a bit confused, should I wait until you fork and then branch? Or go ahead and merge whatever's here?

**Comment by captainwasabi** [comment]
yeah go ahead and merge.  sorry.

**Comment by you-win** [comment]
Thanks for the PR!

**Pull request merged**
